const caseStudiesContent = {
  "att-agentic-security-review": {
    title: "Agentic AI Security Review Workflow",
    org: "AT&T — AI Security & Governance Engineering",
    date: "Jan 2026 – Present",
    tags: ["Agentic AI", "AI Governance", "Security Review", "Enterprise"],
    tldr:
      "A multi-agent workflow that cut enterprise AI security review from 10–12 days to under 6 minutes — without giving the AI unchecked authority.",
    overview:
      "The enterprise AI use-case review process depended on manual security and governance reviewers gathering evidence and handing cases off between teams, taking 10–12 days and creating inconsistent, low-visibility reviews.",
    myRoleHeading: "My Role",
    myRole: [
      "Designed the multi-agent review workflow — intake, analysis, routing, evidence.",
      "Set the security guardrails so agents assist, never decide.",
      "Built the metrics and audit trail reviewers actually use.",
      "Ran adversarial tests and turned failures into fixes.",
    ],
    flowHeading: "Architecture & Workflow",
    flowSteps: [
      { title: "Intake", description: "Collect structured information about the AI use case — data, models, users, tools, deployment environment, and intended actions." },
      { title: "Validation", description: "Verify required fields, reject malformed inputs, and flag missing evidence before analysis begins." },
      { title: "Specialized Review Agents", description: "Independently assess data privacy, security architecture, LLM/agent risk, access control, operational monitoring, and governance requirements." },
      { title: "Evidence Grounding", description: "Link every finding to submitted architecture, data-flow information, and security-control evidence instead of allowing unsupported conclusions." },
      { title: "Risk Aggregation", description: "Normalize findings, remove duplicates, assign severity, and identify control gaps." },
      { title: "Escalation & Approval", description: "Route high-risk or low-confidence cases to human reviewers — final approval stays outside unrestricted model control." },
      { title: "Reporting", description: "Generate an auditable review package, remediation tasks, status, exceptions, and operational metrics." },
    ],
    controlsHeading: "Security Controls",
    controlsPipeline: false,
    controls: [
      { title: "Least-Privilege Tool Access", description: "Separate identities for distinct workflow components, each scoped to only what it needs." },
      { title: "Structured Schemas", description: "Allowlisted tools/actions and deterministic policy checks instead of free-form model authority." },
      { title: "Human Approval Gates", description: "High-impact decisions and exceptions require human sign-off — the model recommends, it doesn't decide." },
      { title: "Full Traceability", description: "Prompt, tool-call, evidence, decision, and output logging for audit." },
      { title: "Adversarial Testing", description: "Prompt-injection and indirect-injection testing, including malicious instructions embedded in uploaded evidence." },
      { title: "Data Handling Limits", description: "Sensitive-data handling requirements, output filtering, and limits on what context reaches the model." },
      { title: "Resilience Controls", description: "Timeouts, retries, defined failure states, rate limits, and fallback paths instead of silent failure." },
      { title: "Independent Evaluation", description: "Regression testing before every workflow change was released." },
    ],
    stats: [
      { value: "10–12 days → <6 min", label: "Review cycle time" },
      { value: "100%", label: "High-risk decisions kept under human approval" },
      { value: "0", label: "Unrestricted model authority granted" },
    ],
    resultsHeading: "Results",
    results: [
      "10–12 days → under 6 minutes per review.",
      "Standardized checks replaced ad-hoc, inconsistent reviews.",
      "Full SLA, exception, and remediation visibility for stakeholders.",
      "Humans still approve every high-risk decision.",
    ],
    references: [],
  },

  "lima-pentestthinkingmcp": {
    title: "LIMA & PentestThinkingMCP — LLM-Driven Attack Simulation",
    org: "University of Houston — First Author, IEEE FMLDS 2025",
    date: "Sep 2024 – May 2025",
    tags: ["Attack Simulation", "MCP", "Purple Team", "Published Research"],
    tldr:
      "First-author research benchmarking how far an LLM can get in a real penetration test — solved 12 of 15 HackTheBox machines autonomously for about $0.05 each.",
    overview:
      "Security teams lacked a rigorous, quantitative way to measure how far an off-the-shelf LLM could autonomously progress from reconnaissance to initial access. LIMA separates the model's reasoning from execution, connects it to real security tools, and benchmarks it against human testers under controlled conditions.",
    myRoleHeading: "My Role",
    myRole: [
      "First author — designed the PentestThinkingMCP reasoning server.",
      "Connected the LLM to Nmap, Metasploit, and Burp Suite via MCP.",
      "Built attack planning with beam search, MCTS, and live feedback.",
      "Designed the human-vs-AI evaluation across five targets.",
    ],
    flowHeading: "Attack-Simulation Workflow",
    flowSteps: [
      { title: "Define Scope", description: "Set the authorized target, initial-access objective, available tools, operator restrictions, and stopping conditions." },
      { title: "Reconnaissance", description: "Use RustScan/Nmap and approved reconnaissance tools to identify ports, services, banners, and candidate entry points." },
      { title: "Reasoning Handoff", description: "Send system state and tool output through the MCP client to the domain-aware PentestThinkingMCP server." },
      { title: "Attack Planning", description: "Map services to possible vulnerabilities, prioritize attack paths, and recommend specific tools with rationale and path scores." },
      { title: "Execution", description: "Run the selected action in the isolated Linux VM and feed the result, error, or changed system state back into the reasoning loop." },
      { title: "Adaptation", description: "Adjust the plan based on observed feedback, including failed exploits, missing dependencies, permissions, and non-standard configurations." },
      { title: "Measurement", description: "Record success, completion time, steps, human intervention, token consumption, cost, and recurring error categories." },
    ],
    controlsHeading: "Implementation & Safety Controls",
    controlsPipeline: false,
    controls: [
      { title: "Scoped Authorization", description: "Explicit authorization, target scoping, isolated test environments, and defined stopping conditions." },
      { title: "Modular Tool Access", description: "Tool access runs through MCP servers instead of treating unconstrained natural-language output as executable authority." },
      { title: "Structured Contracts", description: "Structured tool inputs/outputs and validation contracts to reduce command injection, output ambiguity, and execution drift." },
      { title: "Rate & Cost Limits", description: "Execution timeouts, token/cost monitoring, and bounded retry behavior." },
      { title: "Trust Boundary", description: "Tool output and external content are separated from trusted control instructions, with prompt-injection defenses." },
      { title: "Human Handoff", description: "Human intervention required for CAPTCHA, GUI-bound, ambiguous, privileged, or destructive actions." },
      { title: "Full Logging", description: "Complete logging of prompts, commands, outputs, errors, steps, assistance, model usage, and results for reproducibility." },
    ],
    stats: [
      { value: "12 / 15", label: "HTB boxes solved autonomously by Claude 3.5" },
      { value: "~$0.05", label: "Cost per fully autonomous run" },
      { value: "<5 min", label: "Avg. time for a beginner assisted by LIMA" },
      { value: "5", label: "Controlled targets evaluated" },
    ],
    resultsHeading: "Evaluation Results",
    results: [
      "5 targets, 6 vulnerability classes — from RCE to SQL injection.",
      "LIMA-assisted beginners beat the expert tester on 2 of 5 targets.",
      "Full autonomous runs cost as little as $0.05.",
      "4 recurring failure modes documented for the next version.",
    ],
    references: [
      { label: "Download LIMA Paper (PDF)", url: "/lima-paper.pdf" },
      { label: "PentestThinkingMCP on GitHub", url: "https://github.com/ibrahimsaleem/PentestThinkingMCP" },
    ],
  },

  "nov-mud-report-automation": {
    title: "Self-Improving Mud Report Automation",
    org: "NOV Inc. — IADC/SPE 230772, featured in Drilling Contractor",
    date: "June 2025 – Dec 2025",
    tags: ["Agentic AI", "GenAI", "Evaluation", "Published Research"],
    tldr:
      "Turned a static-prompt PDF parser into a self-improving system — cutting prompt-development time from 960 minutes to 8.8.",
    overview:
      "Daily mud reports arrive as multi-page PDFs with complex tables and layouts that vary across vendors and wells. The original system used static prompts — it worked on known formats, but had no way to measure accuracy or adapt to new templates.",
    myRoleHeading: "My Role",
    myRole: [
      "Designed the core self-improvement logic and vendor-detection path.",
      "Built the prompt-generation, optimization, and dynamic prompt registry.",
      "Introduced the ground-truth evaluation database and accuracy scoring.",
      "Defined human review for new vendors and outliers.",
    ],
    flowHeading: "End-to-End Workflow",
    flowSteps: [
      { title: "Ingestion", description: "Collect incoming mud-report PDFs from the approved enterprise source and associate them with report metadata." },
      { title: "Extraction", description: "Preserve text, table structure, images, vendor names, API well numbers, and other key fields in an LLM-readable representation." },
      { title: "Vendor Detection", description: "Determine whether a report belongs to a known vendor/template or represents an unfamiliar structure." },
      { title: "Known-Vendor Path", description: "Retrieve the approved vendor-specific prompt from the dynamic prompt registry and run structured extraction." },
      { title: "New-Vendor Path", description: "Activate prompt-generation and optimization agents that study historical examples and draft an initial vendor-specific prompt." },
      { title: "Structured Parsing", description: "Convert the report into standardized fields suitable for centralized storage and downstream analytics." },
      { title: "Ground-Truth Comparison", description: "Compare generated fields against records manually verified by a drilling engineer." },
      { title: "Accuracy Assessment", description: "Calculate field-level and report-level accuracy, identify missing/incorrect values, and classify error patterns." },
      { title: "Controlled Self-Improvement", description: "Feed evaluation results back to the prompt agents — a candidate improvement is generated, retested, and stored only if it passes validation criteria." },
      { title: "Human Approval & Monitoring", description: "Human review is retained for new vendors, structural changes, low-confidence outputs, outliers, and production exceptions." },
    ],
    insightHeading: "Why the Evaluation Database Mattered",
    insightText:
      "Without it, self-improvement would be unsafe to trust — a model could change a prompt and quietly reduce accuracy. Every candidate prompt had to beat the production prompt on human-verified records before it could replace it, with full rollback history.",
    controlsHeading: "Risks Considered & Controls",
    controlsPipeline: false,
    controls: [
      { title: "Prompt Injection", description: "Malicious instructions embedded in PDF text, tables, images, or engineering remarks." },
      { title: "Data Exposure", description: "Sensitive operational data exposure through model prompts, logs, or external model endpoints." },
      { title: "Silent Regression", description: "Model-generated prompt changes that raise average accuracy but damage critical fields or a specific vendor." },
      { title: "Data Poisoning", description: "Poisoning risk in the historical examples or ground-truth records used by the agents." },
      { title: "Extraction Failures", description: "OCR errors, malformed PDFs, missing pages, layout drift, or image-only fields." },
      { title: "Runaway Optimization", description: "Infinite optimization loops, unnecessary model calls, cost growth, and non-deterministic behavior." },
      { title: "Provenance Gaps", description: "Ability to trace which report, extraction output, prompt version, and evaluation record produced a final value." },
    ],
    stats: [
      { value: "960 → 8.8 min", label: "Prompt-development time per report" },
      { value: "2–8%", label: "Accuracy gain: AI-generated vs. manual prompts" },
      { value: "~6%", label: "Avg. accuracy gain from self-improvement loop" },
    ],
    resultsHeading: "Results & External Validation",
    results: [
      "960 min → 8.8 min average prompt-development time.",
      "2–8% accuracy gain from AI-generated vs. manual prompts.",
      "~6% average gain from the self-improvement loop.",
      "Published as IADC/SPE 230772, featured in Drilling Contractor.",
    ],
    references: [
      { label: "Read the Drilling Contractor Article", url: "https://drillingcontractor.org/generative-ai-agents-reduce-manual-labor-in-extraction-digitalization-of-mud-report-data-78857" },
      { label: "View the IADC/SPE 230772 Paper Record", url: "https://onepetro.org/SPEDC/proceedings-abstract/26DC/26DC/796172" },
    ],
  },

  "nov-email-routing-automation": {
    title: "Enterprise AI Email-Routing Automation",
    org: "NOV Inc.",
    date: "June 2025 – Dec 2025",
    tags: ["Workflow Automation", "Threat Modeling", "OWASP LLM Top 10"],
    tldr:
      "Automated 50+ daily inbound inquiries at ~95% routing accuracy — without giving the model free rein over recipients.",
    overview:
      "NOV received 50+ \"Contact Us\" inquiries per day that employees had to manually read and forward to the right team, costing 20+ hours a week and risking inconsistent or unsafe routing.",
    myRoleHeading: "My Role",
    myRole: [
      "Designed the intent-based routing workflow and confidence thresholds.",
      "Threat-modeled prompt injection and sensitive-data exposure.",
      "Built destination allowlists so the model can't freelance.",
      "Measured accuracy and tuned prompts from real failures.",
    ],
    flowHeading: "Implementation Workflow",
    flowSteps: [
      { title: "Ingest", description: "Extract relevant fields from the message: contact information, location, topic, and requested service." },
      { title: "Sanitize & Classify", description: "Classify untrusted content without treating the sender's text as trusted instructions." },
      { title: "Context Retrieval", description: "Retrieve only the approved company information needed for routing." },
      { title: "Routing Decision", description: "Generate a structured routing decision with destination, reason, and confidence." },
      { title: "Rule Enforcement", description: "Apply deterministic business rules and destination allowlists." },
      { title: "Escalation", description: "Route low-confidence or sensitive cases to a human rather than auto-forwarding." },
      { title: "Monitoring", description: "Record the decision and outcome for quality review and troubleshooting." },
    ],
    controlsHeading: "Threat Model & Controls",
    controlsPipeline: false,
    controls: [
      { title: "Untrusted Input", description: "Inbound email is treated as untrusted content, not as instructions to the model." },
      { title: "Prompt Injection", description: "Tested direct and indirect prompt injection embedded in message text." },
      { title: "Destination Allowlists", description: "The model cannot select arbitrary recipients — routing is checked against deterministic rules." },
      { title: "Sensitive Data Exposure", description: "Limits on what internal context the model can retrieve or expose." },
      { title: "Excessive Agency", description: "Low-confidence or sensitive cases escalate to a human instead of auto-routing." },
      { title: "Auditability", description: "Every decision and outcome is logged for quality review." },
    ],
    stats: [
      { value: "~95%", label: "Routing accuracy" },
      { value: "20+ hrs/wk", label: "Manual forwarding effort eliminated" },
      { value: "50+", label: "Inquiries handled daily" },
    ],
    resultsHeading: "Results",
    results: [
      "~95% routing accuracy across inquiry categories.",
      "20+ hours of weekly manual effort eliminated.",
      "50+ inquiries handled daily, fully automated.",
      "Model never granted direct access to recipients.",
    ],
    references: [],
  },
};

export default caseStudiesContent;
