const caseStudiesContent = {
  "att-agentic-security-review": {
    title: "Agentic AI Security Review Workflow",
    org: "AT&T — AI Security & Governance Engineering",
    date: "Jan 2026 – Present",
    tags: ["Agentic AI", "AI Governance", "Security Review", "Enterprise"],
    overview:
      "The enterprise AI use-case review and permit-to-build/operate process depended on multiple manual security and governance reviewers gathering evidence and handing cases off between teams. The process could take approximately 10 to 12 days, creating inconsistent reviews, limited visibility into bottlenecks, and delays in responsible AI deployment.",
    myRoleHeading: "My Role",
    myRole: [
      "Helped design a multi-agent workflow that collects use-case information, performs specialized security and governance analysis, routes exceptions, and produces review evidence.",
      "Defined security controls so the agents could assist reviewers without receiving unrestricted authority.",
      "Built operational metrics, escalation logic, and audit evidence suitable for enterprise stakeholders.",
      "Performed adversarial testing and translated failures into requirements, detections, and remediation actions.",
    ],
    flowHeading: "Architecture & Workflow",
    flowSteps: [
      { title: "Intake", description: "Collect structured information about the AI use case — data, models, users, tools, deployment environment, and intended actions." },
      { title: "Validation", description: "Verify required fields, reject malformed inputs, and flag missing evidence before analysis begins." },
      { title: "Specialized Review Agents", description: "Independently assess data privacy, security architecture, LLM/agent risk, access control, operational monitoring, and governance requirements." },
      { title: "Evidence Grounding", description: "Link every finding to submitted architecture, data-flow information, and security-control evidence instead of allowing unsupported conclusions." },
      { title: "Risk Aggregation", description: "Normalize findings, remove duplicates, assign severity, and identify control gaps." },
      { title: "Escalation & Approval", description: "Route high-risk or low-confidence cases to human reviewers — final approval stays outside unrestricted model control." },
      { title: "Reporting", description: "Generate an auditable review package, remediation tasks, status, exceptions, and operational metrics." },
    ],
    controlsHeading: "Security Controls",
    controlsPipeline: false,
    controls: [
      { title: "Least-Privilege Tool Access", description: "Separate identities for distinct workflow components, each scoped to only what it needs." },
      { title: "Structured Schemas", description: "Allowlisted tools/actions and deterministic policy checks instead of free-form model authority." },
      { title: "Human Approval Gates", description: "High-impact decisions and exceptions require human sign-off — the model recommends, it doesn't decide." },
      { title: "Full Traceability", description: "Prompt, tool-call, evidence, decision, and output logging for audit." },
      { title: "Adversarial Testing", description: "Prompt-injection and indirect-injection testing, including malicious instructions embedded in uploaded evidence." },
      { title: "Data Handling Limits", description: "Sensitive-data handling requirements, output filtering, and limits on what context reaches the model." },
      { title: "Resilience Controls", description: "Timeouts, retries, defined failure states, rate limits, and fallback paths instead of silent failure." },
      { title: "Independent Evaluation", description: "Regression testing before every workflow change was released." },
    ],
    stats: [
      { value: "10–12 days → <6 min", label: "Review cycle time" },
      { value: "100%", label: "High-risk decisions kept under human approval" },
      { value: "0", label: "Unrestricted model authority granted" },
    ],
    resultsHeading: "Results",
    results: [
      "Reduced the review cycle from approximately 10–12 days to under six minutes for automated workflow execution.",
      "Improved consistency through standardized checks and structured evidence capture.",
      "Increased visibility through SLA, risk-exception, queue-aging, control-status, and remediation reporting.",
      "Preserved human authority for approval and high-risk exceptions rather than treating AI output as final truth.",
    ],
    references: [],
  },

  "lima-pentestthinkingmcp": {
    title: "LIMA & PentestThinkingMCP — LLM-Driven Attack Simulation",
    org: "University of Houston — First Author, IEEE FMLDS 2025",
    date: "Sep 2024 – May 2025",
    tags: ["Attack Simulation", "MCP", "Purple Team", "Published Research"],
    overview:
      "Security teams lacked a rigorous, quantitative way to determine how far an off-the-shelf LLM could autonomously progress from reconnaissance to initial access. Existing work often demonstrated isolated tasks or depended heavily on manual guidance. LIMA was designed to separate the model's reasoning from execution mechanics, connect the model to approved security tools, evaluate it against human testers under controlled conditions, and document both capability and failure modes.",
    myRoleHeading: "My Role",
    myRole: [
      "Led the research as first author and designed the custom PentestThinkingMCP reasoning server used in the LIMA architecture.",
      "Designed a modular MCP architecture connecting the LLM to a Linux testing VM, Nmap, Metasploit, FilesystemMCP, BrowserMCP, WebSearchMCP, and controlled target systems.",
      "Implemented context-aware attack planning using port/service mappings, CVE knowledge, Beam Search for efficient planning, MCTS for exploration, structured outputs, and feedback loops from tool execution.",
      "Designed the evaluation protocol comparing Claude 3.5, GPT-4o, an expert tester, a beginner tester, and a beginner assisted by LIMA across four HackTheBox machines and one custom VM.",
    ],
    flowHeading: "Attack-Simulation Workflow",
    flowSteps: [
      { title: "Define Scope", description: "Set the authorized target, initial-access objective, available tools, operator restrictions, and stopping conditions." },
      { title: "Reconnaissance", description: "Use RustScan/Nmap and approved reconnaissance tools to identify ports, services, banners, and candidate entry points." },
      { title: "Reasoning Handoff", description: "Send system state and tool output through the MCP client to the domain-aware PentestThinkingMCP server." },
      { title: "Attack Planning", description: "Map services to possible vulnerabilities, prioritize attack paths, and recommend specific tools with rationale and path scores." },
      { title: "Execution", description: "Run the selected action in the isolated Linux VM and feed the result, error, or changed system state back into the reasoning loop." },
      { title: "Adaptation", description: "Adjust the plan based on observed feedback, including failed exploits, missing dependencies, permissions, and non-standard configurations." },
      { title: "Measurement", description: "Record success, completion time, steps, human intervention, token consumption, cost, and recurring error categories." },
    ],
    controlsHeading: "Implementation & Safety Controls",
    controlsPipeline: false,
    controls: [
      { title: "Scoped Authorization", description: "Explicit authorization, target scoping, isolated test environments, and defined stopping conditions." },
      { title: "Modular Tool Access", description: "Tool access runs through MCP servers instead of treating unconstrained natural-language output as executable authority." },
      { title: "Structured Contracts", description: "Structured tool inputs/outputs and validation contracts to reduce command injection, output ambiguity, and execution drift." },
      { title: "Rate & Cost Limits", description: "Execution timeouts, token/cost monitoring, and bounded retry behavior." },
      { title: "Trust Boundary", description: "Tool output and external content are separated from trusted control instructions, with prompt-injection defenses." },
      { title: "Human Handoff", description: "Human intervention required for CAPTCHA, GUI-bound, ambiguous, privileged, or destructive actions." },
      { title: "Full Logging", description: "Complete logging of prompts, commands, outputs, errors, steps, assistance, model usage, and results for reproducibility." },
    ],
    stats: [
      { value: "12 / 15", label: "HTB boxes solved autonomously by Claude 3.5" },
      { value: "~$0.05", label: "Cost per fully autonomous run" },
      { value: "<5 min", label: "Avg. time for a beginner assisted by LIMA" },
      { value: "5", label: "Controlled targets evaluated" },
    ],
    resultsHeading: "Evaluation Results",
    results: [
      "Evaluated five controlled targets — LAME, TwoMillion, Support, PC, and a custom Exam Box — covering remote code execution, command injection, credential disclosure, SQL injection, enumeration, and SSH access.",
      "Compared model-only, human-only, and human-plus-LLM conditions; LIMA-assisted beginner testing averaged under five minutes and outpaced the expert tester on two targets.",
      "Model-only runs performed strongly on straightforward, knowledge-retrieval-heavy targets, with full autonomous runs costing no more than roughly $0.05.",
      "Documented four recurring error classes: local-optimum retry loops, modality gaps (GUI/CAPTCHA barriers), environment-coupling faults, and brittleness under non-standard configurations.",
    ],
    references: [
      { label: "Download LIMA Paper (PDF)", url: "/lima-paper.pdf" },
      { label: "PentestThinkingMCP on GitHub", url: "https://github.com/ibrahimsaleem/PentestThinkingMCP" },
    ],
  },

  "nov-mud-report-automation": {
    title: "Self-Improving Mud Report Automation",
    org: "NOV Inc. — IADC/SPE 230772, featured in Drilling Contractor",
    date: "June 2025 – Dec 2025",
    tags: ["Agentic AI", "GenAI", "Evaluation", "Published Research"],
    overview:
      "Daily mud reports contain critical drilling and fluid data, but arrive as multi-page PDFs with complex tables, unstructured text, images, vendor-specific terminology, and layouts that vary across vendors, wells, and dates. The original system was a basic static-prompt workflow: it could parse known formats, but had no centralized ground-truth evaluation database, no automated accuracy-assessment module, and no controlled self-improvement mechanism for new or changing templates.",
    myRoleHeading: "My Role",
    myRole: [
      "Contributing designer of the core agentic logic that turned the static workflow into a self-improving system.",
      "Designed the vendor-identification path that determined whether a report matched a known template or required adaptation.",
      "Designed the automatic prompt-generation and optimization agents, the dynamic prompt registry, and the feedback loop used to improve vendor-specific extraction prompts.",
      "Introduced the ground-truth evaluation database and accuracy-assessment logic so model output could be measured against human-verified records instead of judged subjectively.",
      "Helped define human-in-the-loop calibration, exception handling, and validation procedures for onboarding new vendors and detecting outliers.",
    ],
    flowHeading: "End-to-End Workflow",
    flowSteps: [
      { title: "Ingestion", description: "Collect incoming mud-report PDFs from the approved enterprise source and associate them with report metadata." },
      { title: "Extraction", description: "Preserve text, table structure, images, vendor names, API well numbers, and other key fields in an LLM-readable representation." },
      { title: "Vendor Detection", description: "Determine whether a report belongs to a known vendor/template or represents an unfamiliar structure." },
      { title: "Known-Vendor Path", description: "Retrieve the approved vendor-specific prompt from the dynamic prompt registry and run structured extraction." },
      { title: "New-Vendor Path", description: "Activate prompt-generation and optimization agents that study historical examples and draft an initial vendor-specific prompt." },
      { title: "Structured Parsing", description: "Convert the report into standardized fields suitable for centralized storage and downstream analytics." },
      { title: "Ground-Truth Comparison", description: "Compare generated fields against records manually verified by a drilling engineer." },
      { title: "Accuracy Assessment", description: "Calculate field-level and report-level accuracy, identify missing/incorrect values, and classify error patterns." },
      { title: "Controlled Self-Improvement", description: "Feed evaluation results back to the prompt agents — a candidate improvement is generated, retested, and stored only if it passes validation criteria." },
      { title: "Human Approval & Monitoring", description: "Human review is retained for new vendors, structural changes, low-confidence outputs, outliers, and production exceptions." },
    ],
    insightHeading: "Why the Evaluation Database Mattered",
    insightText:
      "Without a ground-truth database, self-improvement would be unsafe and unmeasurable — a model could change a prompt and appear more confident while silently reducing data quality. The evaluation database created an objective baseline: every candidate prompt was tested against human-verified records, compared with the current production prompt, and rejected if it caused regression in critical fields or overall accuracy. The production prompt was never overwritten simply because an agent proposed a change — the change had to demonstrate measurable improvement, and prompt versions, test results, and rollback information were retained for traceability.",
    controlsHeading: "Risks Considered & Controls",
    controlsPipeline: false,
    controls: [
      { title: "Prompt Injection", description: "Malicious instructions embedded in PDF text, tables, images, or engineering remarks." },
      { title: "Data Exposure", description: "Sensitive operational data exposure through model prompts, logs, or external model endpoints." },
      { title: "Silent Regression", description: "Model-generated prompt changes that raise average accuracy but damage critical fields or a specific vendor." },
      { title: "Data Poisoning", description: "Poisoning risk in the historical examples or ground-truth records used by the agents." },
      { title: "Extraction Failures", description: "OCR errors, malformed PDFs, missing pages, layout drift, or image-only fields." },
      { title: "Runaway Optimization", description: "Infinite optimization loops, unnecessary model calls, cost growth, and non-deterministic behavior." },
      { title: "Provenance Gaps", description: "Ability to trace which report, extraction output, prompt version, and evaluation record produced a final value." },
    ],
    stats: [
      { value: "960 → 8.8 min", label: "Prompt-development time per report" },
      { value: "2–8%", label: "Accuracy gain: AI-generated vs. manual prompts" },
      { value: "~6%", label: "Avg. accuracy gain from self-improvement loop" },
    ],
    resultsHeading: "Results & External Validation",
    results: [
      "Manual prompt creation took approximately 960 minutes per report; the AI agents produced prompts of equivalent quality in an average of 8.8 minutes.",
      "AI-generated prompts improved average parsing accuracy by approximately 2–8% compared with manual prompts in the reported test.",
      "In the self-improvement test, the agents achieved an average parsing-accuracy improvement of approximately 6% across the evaluated vendors.",
      "The work was accepted as IADC/SPE 230772 and featured in the July/August 2026 issue of Drilling Contractor.",
    ],
    references: [
      { label: "Read the Drilling Contractor Article", url: "https://drillingcontractor.org/generative-ai-agents-reduce-manual-labor-in-extraction-digitalization-of-mud-report-data-78857" },
      { label: "View the IADC/SPE 230772 Paper Record", url: "https://onepetro.org/SPEDC/proceedings-abstract/26DC/26DC/796172" },
    ],
  },

  "nov-email-routing-automation": {
    title: "Enterprise AI Email-Routing Automation",
    org: "NOV Inc.",
    date: "June 2025 – Dec 2025",
    tags: ["Workflow Automation", "Threat Modeling", "OWASP LLM Top 10"],
    overview:
      "NOV received more than 50 \"Contact Us\" inquiries per day that required employees to manually interpret each request and forward it to the correct person or team. This consumed more than 20 staff hours each week and created delays, inconsistent routing, and the risk of sending sensitive or malicious content into downstream workflows.",
    myRoleHeading: "My Role",
    myRole: [
      "Designed an AI assistant and automation workflow that used user intent, message content, location, and approved company context to select the correct routing destination.",
      "Defined validation logic and exception handling for low-confidence, ambiguous, or unsupported requests.",
      "Threat-modeled direct and indirect prompt injection, sensitive-data exposure, excessive agency, and malicious attachments/content.",
      "Measured routing accuracy and reviewed failure categories to improve prompts and workflow rules.",
    ],
    flowHeading: "Implementation Workflow",
    flowSteps: [
      { title: "Ingest", description: "Extract relevant fields from the message: contact information, location, topic, and requested service." },
      { title: "Sanitize & Classify", description: "Classify untrusted content without treating the sender's text as trusted instructions." },
      { title: "Context Retrieval", description: "Retrieve only the approved company information needed for routing." },
      { title: "Routing Decision", description: "Generate a structured routing decision with destination, reason, and confidence." },
      { title: "Rule Enforcement", description: "Apply deterministic business rules and destination allowlists." },
      { title: "Escalation", description: "Route low-confidence or sensitive cases to a human rather than auto-forwarding." },
      { title: "Monitoring", description: "Record the decision and outcome for quality review and troubleshooting." },
    ],
    controlsHeading: "Threat Model & Controls",
    controlsPipeline: false,
    controls: [
      { title: "Untrusted Input", description: "Inbound email is treated as untrusted content, not as instructions to the model." },
      { title: "Prompt Injection", description: "Tested direct and indirect prompt injection embedded in message text." },
      { title: "Destination Allowlists", description: "The model cannot select arbitrary recipients — routing is checked against deterministic rules." },
      { title: "Sensitive Data Exposure", description: "Limits on what internal context the model can retrieve or expose." },
      { title: "Excessive Agency", description: "Low-confidence or sensitive cases escalate to a human instead of auto-routing." },
      { title: "Auditability", description: "Every decision and outcome is logged for quality review." },
    ],
    stats: [
      { value: "~95%", label: "Routing accuracy" },
      { value: "20+ hrs/wk", label: "Manual forwarding effort eliminated" },
      { value: "50+", label: "Inquiries handled daily" },
    ],
    resultsHeading: "Results",
    results: [
      "Achieved approximately 95% routing accuracy across inquiry categories.",
      "Eliminated more than 20 hours of weekly manual forwarding effort.",
      "Handled more than 50 messages daily through a controlled AI-assisted workflow.",
      "Demonstrated that business automation can improve throughput without giving the model unrestricted access to recipients or internal information.",
    ],
    references: [],
  },
};

export default caseStudiesContent;
